name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Discard automated changes to GitHub workflows
        run: git checkout HEAD -- .github/
        
      - name: Run Prettier Formatter
        run: npx prettier --write .

      - name: Trigger Autofix
        uses: autofix-ci/action@v1
