name: autofix.ci

on:
  workflow_dispatch: 
  #pull_request:
  #push:
    #branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs Prettier directly over all files without needing an npm install step
      - name: Run Prettier Formatter
        run: npx prettier --write .

      - name: Trigger Autofix
        uses: autofix-ci/action@v1
